In [2]:
%pip install chompjs
import sys
sys.path.append('../src')
from showdown_parser import ShowdownDataParser

Collecting chompjs
  Using cached chompjs-1.4.0-cp313-cp313-win_amd64.whl.metadata (8.0 kB)
Using cached chompjs-1.4.0-cp313-cp313-win_amd64.whl (18 kB)
Installing collected packages: chompjs
Successfully installed chompjs-1.4.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
parser = ShowdownDataParser()

# 1. Fetch Moves
df_moves = parser.build_move_database()
display(df_moves[df_moves['name'] == 'Extreme Speed'])

# 2. Fetch Abilities
df_abilities = parser.build_ability_database()
display(df_abilities[df_abilities['name'] == 'Intimidate'])

Downloading mechanical move data from Pokémon Showdown...
Saved 951 moves to ../data/raw\showdown_moves.csv

,id,name,type,category,base_power,accuracy,priority,target,flags
232,extremespeed,Extreme Speed,normal,Physical,80,100,2,normal,"{""contact"": 1, ""protect"": 1, ""mirror"": 1, ""met..."

Downloading mechanical ability data from Pokémon Showdown...
Saved 314 abilities to ../data/raw\showdown_abilities.csv

,id,name,short_desc,rating
118,intimidate,Intimidate,"On switch-in, this Pokemon lowers the Attack o...",3.5